//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace highlight_system.ServiceReferencePlot {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://singlepanelplotting.aseglobal.com/", ConfigurationName="ServiceReferencePlot.SinglePanelPlotSoap")]
    public interface SinglePanelPlotSoap {
        
        // CODEGEN: 命名空間 http://singlepanelplotting.aseglobal.com/ 的元素名稱  GetNowTimeResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://singlepanelplotting.aseglobal.com/GetNowTime", ReplyAction="*")]
        highlight_system.ServiceReferencePlot.GetNowTimeResponse GetNowTime(highlight_system.ServiceReferencePlot.GetNowTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://singlepanelplotting.aseglobal.com/GetNowTime", ReplyAction="*")]
        System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.GetNowTimeResponse> GetNowTimeAsync(highlight_system.ServiceReferencePlot.GetNowTimeRequest request);
        
        // CODEGEN: 命名空間 http://singlepanelplotting.aseglobal.com/ 的元素名稱  site 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://singlepanelplotting.aseglobal.com/Plot", ReplyAction="*")]
        highlight_system.ServiceReferencePlot.PlotResponse Plot(highlight_system.ServiceReferencePlot.PlotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://singlepanelplotting.aseglobal.com/Plot", ReplyAction="*")]
        System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.PlotResponse> PlotAsync(highlight_system.ServiceReferencePlot.PlotRequest request);
        
        // CODEGEN: 命名空間 http://singlepanelplotting.aseglobal.com/ 的元素名稱  site 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://singlepanelplotting.aseglobal.com/Plot_Alldefect", ReplyAction="*")]
        highlight_system.ServiceReferencePlot.Plot_AlldefectResponse Plot_Alldefect(highlight_system.ServiceReferencePlot.Plot_AlldefectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://singlepanelplotting.aseglobal.com/Plot_Alldefect", ReplyAction="*")]
        System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.Plot_AlldefectResponse> Plot_AlldefectAsync(highlight_system.ServiceReferencePlot.Plot_AlldefectRequest request);
        
        // CODEGEN: 命名空間 http://singlepanelplotting.aseglobal.com/ 的元素名稱  site 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://singlepanelplotting.aseglobal.com/Plot_SinglePanel", ReplyAction="*")]
        highlight_system.ServiceReferencePlot.Plot_SinglePanelResponse Plot_SinglePanel(highlight_system.ServiceReferencePlot.Plot_SinglePanelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://singlepanelplotting.aseglobal.com/Plot_SinglePanel", ReplyAction="*")]
        System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.Plot_SinglePanelResponse> Plot_SinglePanelAsync(highlight_system.ServiceReferencePlot.Plot_SinglePanelRequest request);
        
        // CODEGEN: 命名空間 http://singlepanelplotting.aseglobal.com/ 的元素名稱  site 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://singlepanelplotting.aseglobal.com/Plot_AllSinglePanel", ReplyAction="*")]
        highlight_system.ServiceReferencePlot.Plot_AllSinglePanelResponse Plot_AllSinglePanel(highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://singlepanelplotting.aseglobal.com/Plot_AllSinglePanel", ReplyAction="*")]
        System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.Plot_AllSinglePanelResponse> Plot_AllSinglePanelAsync(highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNowTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNowTime", Namespace="http://singlepanelplotting.aseglobal.com/", Order=0)]
        public highlight_system.ServiceReferencePlot.GetNowTimeRequestBody Body;
        
        public GetNowTimeRequest() {
        }
        
        public GetNowTimeRequest(highlight_system.ServiceReferencePlot.GetNowTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNowTimeRequestBody {
        
        public GetNowTimeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNowTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNowTimeResponse", Namespace="http://singlepanelplotting.aseglobal.com/", Order=0)]
        public highlight_system.ServiceReferencePlot.GetNowTimeResponseBody Body;
        
        public GetNowTimeResponse() {
        }
        
        public GetNowTimeResponse(highlight_system.ServiceReferencePlot.GetNowTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singlepanelplotting.aseglobal.com/")]
    public partial class GetNowTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNowTimeResult;
        
        public GetNowTimeResponseBody() {
        }
        
        public GetNowTimeResponseBody(string GetNowTimeResult) {
            this.GetNowTimeResult = GetNowTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Plot", Namespace="http://singlepanelplotting.aseglobal.com/", Order=0)]
        public highlight_system.ServiceReferencePlot.PlotRequestBody Body;
        
        public PlotRequest() {
        }
        
        public PlotRequest(highlight_system.ServiceReferencePlot.PlotRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singlepanelplotting.aseglobal.com/")]
    public partial class PlotRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string macid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lotnum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string defectcode;
        
        public PlotRequestBody() {
        }
        
        public PlotRequestBody(string site, string macid, string lotnum, string defectcode) {
            this.site = site;
            this.macid = macid;
            this.lotnum = lotnum;
            this.defectcode = defectcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlotResponse", Namespace="http://singlepanelplotting.aseglobal.com/", Order=0)]
        public highlight_system.ServiceReferencePlot.PlotResponseBody Body;
        
        public PlotResponse() {
        }
        
        public PlotResponse(highlight_system.ServiceReferencePlot.PlotResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singlepanelplotting.aseglobal.com/")]
    public partial class PlotResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PlotResult;
        
        public PlotResponseBody() {
        }
        
        public PlotResponseBody(bool PlotResult) {
            this.PlotResult = PlotResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Plot_AlldefectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Plot_Alldefect", Namespace="http://singlepanelplotting.aseglobal.com/", Order=0)]
        public highlight_system.ServiceReferencePlot.Plot_AlldefectRequestBody Body;
        
        public Plot_AlldefectRequest() {
        }
        
        public Plot_AlldefectRequest(highlight_system.ServiceReferencePlot.Plot_AlldefectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singlepanelplotting.aseglobal.com/")]
    public partial class Plot_AlldefectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string macid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lotnum;
        
        public Plot_AlldefectRequestBody() {
        }
        
        public Plot_AlldefectRequestBody(string site, string macid, string lotnum) {
            this.site = site;
            this.macid = macid;
            this.lotnum = lotnum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Plot_AlldefectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Plot_AlldefectResponse", Namespace="http://singlepanelplotting.aseglobal.com/", Order=0)]
        public highlight_system.ServiceReferencePlot.Plot_AlldefectResponseBody Body;
        
        public Plot_AlldefectResponse() {
        }
        
        public Plot_AlldefectResponse(highlight_system.ServiceReferencePlot.Plot_AlldefectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singlepanelplotting.aseglobal.com/")]
    public partial class Plot_AlldefectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Plot_AlldefectResult;
        
        public Plot_AlldefectResponseBody() {
        }
        
        public Plot_AlldefectResponseBody(bool Plot_AlldefectResult) {
            this.Plot_AlldefectResult = Plot_AlldefectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Plot_SinglePanelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Plot_SinglePanel", Namespace="http://singlepanelplotting.aseglobal.com/", Order=0)]
        public highlight_system.ServiceReferencePlot.Plot_SinglePanelRequestBody Body;
        
        public Plot_SinglePanelRequest() {
        }
        
        public Plot_SinglePanelRequest(highlight_system.ServiceReferencePlot.Plot_SinglePanelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singlepanelplotting.aseglobal.com/")]
    public partial class Plot_SinglePanelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string macid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lotnum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string piece_num;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string defectcode;
        
        public Plot_SinglePanelRequestBody() {
        }
        
        public Plot_SinglePanelRequestBody(string site, string macid, string lotnum, string piece_num, string defectcode) {
            this.site = site;
            this.macid = macid;
            this.lotnum = lotnum;
            this.piece_num = piece_num;
            this.defectcode = defectcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Plot_SinglePanelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Plot_SinglePanelResponse", Namespace="http://singlepanelplotting.aseglobal.com/", Order=0)]
        public highlight_system.ServiceReferencePlot.Plot_SinglePanelResponseBody Body;
        
        public Plot_SinglePanelResponse() {
        }
        
        public Plot_SinglePanelResponse(highlight_system.ServiceReferencePlot.Plot_SinglePanelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singlepanelplotting.aseglobal.com/")]
    public partial class Plot_SinglePanelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Plot_SinglePanelResult;
        
        public Plot_SinglePanelResponseBody() {
        }
        
        public Plot_SinglePanelResponseBody(bool Plot_SinglePanelResult) {
            this.Plot_SinglePanelResult = Plot_SinglePanelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Plot_AllSinglePanelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Plot_AllSinglePanel", Namespace="http://singlepanelplotting.aseglobal.com/", Order=0)]
        public highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequestBody Body;
        
        public Plot_AllSinglePanelRequest() {
        }
        
        public Plot_AllSinglePanelRequest(highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singlepanelplotting.aseglobal.com/")]
    public partial class Plot_AllSinglePanelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string macid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lotnum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string defectcode;
        
        public Plot_AllSinglePanelRequestBody() {
        }
        
        public Plot_AllSinglePanelRequestBody(string site, string macid, string lotnum, string defectcode) {
            this.site = site;
            this.macid = macid;
            this.lotnum = lotnum;
            this.defectcode = defectcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Plot_AllSinglePanelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Plot_AllSinglePanelResponse", Namespace="http://singlepanelplotting.aseglobal.com/", Order=0)]
        public highlight_system.ServiceReferencePlot.Plot_AllSinglePanelResponseBody Body;
        
        public Plot_AllSinglePanelResponse() {
        }
        
        public Plot_AllSinglePanelResponse(highlight_system.ServiceReferencePlot.Plot_AllSinglePanelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singlepanelplotting.aseglobal.com/")]
    public partial class Plot_AllSinglePanelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Plot_AllSinglePanelResult;
        
        public Plot_AllSinglePanelResponseBody() {
        }
        
        public Plot_AllSinglePanelResponseBody(bool Plot_AllSinglePanelResult) {
            this.Plot_AllSinglePanelResult = Plot_AllSinglePanelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SinglePanelPlotSoapChannel : highlight_system.ServiceReferencePlot.SinglePanelPlotSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SinglePanelPlotSoapClient : System.ServiceModel.ClientBase<highlight_system.ServiceReferencePlot.SinglePanelPlotSoap>, highlight_system.ServiceReferencePlot.SinglePanelPlotSoap {
        
        public SinglePanelPlotSoapClient() {
        }
        
        public SinglePanelPlotSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SinglePanelPlotSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SinglePanelPlotSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SinglePanelPlotSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        highlight_system.ServiceReferencePlot.GetNowTimeResponse highlight_system.ServiceReferencePlot.SinglePanelPlotSoap.GetNowTime(highlight_system.ServiceReferencePlot.GetNowTimeRequest request) {
            return base.Channel.GetNowTime(request);
        }
        
        public string GetNowTime() {
            highlight_system.ServiceReferencePlot.GetNowTimeRequest inValue = new highlight_system.ServiceReferencePlot.GetNowTimeRequest();
            inValue.Body = new highlight_system.ServiceReferencePlot.GetNowTimeRequestBody();
            highlight_system.ServiceReferencePlot.GetNowTimeResponse retVal = ((highlight_system.ServiceReferencePlot.SinglePanelPlotSoap)(this)).GetNowTime(inValue);
            return retVal.Body.GetNowTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.GetNowTimeResponse> highlight_system.ServiceReferencePlot.SinglePanelPlotSoap.GetNowTimeAsync(highlight_system.ServiceReferencePlot.GetNowTimeRequest request) {
            return base.Channel.GetNowTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.GetNowTimeResponse> GetNowTimeAsync() {
            highlight_system.ServiceReferencePlot.GetNowTimeRequest inValue = new highlight_system.ServiceReferencePlot.GetNowTimeRequest();
            inValue.Body = new highlight_system.ServiceReferencePlot.GetNowTimeRequestBody();
            return ((highlight_system.ServiceReferencePlot.SinglePanelPlotSoap)(this)).GetNowTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        highlight_system.ServiceReferencePlot.PlotResponse highlight_system.ServiceReferencePlot.SinglePanelPlotSoap.Plot(highlight_system.ServiceReferencePlot.PlotRequest request) {
            return base.Channel.Plot(request);
        }
        
        public bool Plot(string site, string macid, string lotnum, string defectcode) {
            highlight_system.ServiceReferencePlot.PlotRequest inValue = new highlight_system.ServiceReferencePlot.PlotRequest();
            inValue.Body = new highlight_system.ServiceReferencePlot.PlotRequestBody();
            inValue.Body.site = site;
            inValue.Body.macid = macid;
            inValue.Body.lotnum = lotnum;
            inValue.Body.defectcode = defectcode;
            highlight_system.ServiceReferencePlot.PlotResponse retVal = ((highlight_system.ServiceReferencePlot.SinglePanelPlotSoap)(this)).Plot(inValue);
            return retVal.Body.PlotResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.PlotResponse> highlight_system.ServiceReferencePlot.SinglePanelPlotSoap.PlotAsync(highlight_system.ServiceReferencePlot.PlotRequest request) {
            return base.Channel.PlotAsync(request);
        }
        
        public System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.PlotResponse> PlotAsync(string site, string macid, string lotnum, string defectcode) {
            highlight_system.ServiceReferencePlot.PlotRequest inValue = new highlight_system.ServiceReferencePlot.PlotRequest();
            inValue.Body = new highlight_system.ServiceReferencePlot.PlotRequestBody();
            inValue.Body.site = site;
            inValue.Body.macid = macid;
            inValue.Body.lotnum = lotnum;
            inValue.Body.defectcode = defectcode;
            return ((highlight_system.ServiceReferencePlot.SinglePanelPlotSoap)(this)).PlotAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        highlight_system.ServiceReferencePlot.Plot_AlldefectResponse highlight_system.ServiceReferencePlot.SinglePanelPlotSoap.Plot_Alldefect(highlight_system.ServiceReferencePlot.Plot_AlldefectRequest request) {
            return base.Channel.Plot_Alldefect(request);
        }
        
        public bool Plot_Alldefect(string site, string macid, string lotnum) {
            highlight_system.ServiceReferencePlot.Plot_AlldefectRequest inValue = new highlight_system.ServiceReferencePlot.Plot_AlldefectRequest();
            inValue.Body = new highlight_system.ServiceReferencePlot.Plot_AlldefectRequestBody();
            inValue.Body.site = site;
            inValue.Body.macid = macid;
            inValue.Body.lotnum = lotnum;
            highlight_system.ServiceReferencePlot.Plot_AlldefectResponse retVal = ((highlight_system.ServiceReferencePlot.SinglePanelPlotSoap)(this)).Plot_Alldefect(inValue);
            return retVal.Body.Plot_AlldefectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.Plot_AlldefectResponse> highlight_system.ServiceReferencePlot.SinglePanelPlotSoap.Plot_AlldefectAsync(highlight_system.ServiceReferencePlot.Plot_AlldefectRequest request) {
            return base.Channel.Plot_AlldefectAsync(request);
        }
        
        public System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.Plot_AlldefectResponse> Plot_AlldefectAsync(string site, string macid, string lotnum) {
            highlight_system.ServiceReferencePlot.Plot_AlldefectRequest inValue = new highlight_system.ServiceReferencePlot.Plot_AlldefectRequest();
            inValue.Body = new highlight_system.ServiceReferencePlot.Plot_AlldefectRequestBody();
            inValue.Body.site = site;
            inValue.Body.macid = macid;
            inValue.Body.lotnum = lotnum;
            return ((highlight_system.ServiceReferencePlot.SinglePanelPlotSoap)(this)).Plot_AlldefectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        highlight_system.ServiceReferencePlot.Plot_SinglePanelResponse highlight_system.ServiceReferencePlot.SinglePanelPlotSoap.Plot_SinglePanel(highlight_system.ServiceReferencePlot.Plot_SinglePanelRequest request) {
            return base.Channel.Plot_SinglePanel(request);
        }
        
        public bool Plot_SinglePanel(string site, string macid, string lotnum, string piece_num, string defectcode) {
            highlight_system.ServiceReferencePlot.Plot_SinglePanelRequest inValue = new highlight_system.ServiceReferencePlot.Plot_SinglePanelRequest();
            inValue.Body = new highlight_system.ServiceReferencePlot.Plot_SinglePanelRequestBody();
            inValue.Body.site = site;
            inValue.Body.macid = macid;
            inValue.Body.lotnum = lotnum;
            inValue.Body.piece_num = piece_num;
            inValue.Body.defectcode = defectcode;
            highlight_system.ServiceReferencePlot.Plot_SinglePanelResponse retVal = ((highlight_system.ServiceReferencePlot.SinglePanelPlotSoap)(this)).Plot_SinglePanel(inValue);
            return retVal.Body.Plot_SinglePanelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.Plot_SinglePanelResponse> highlight_system.ServiceReferencePlot.SinglePanelPlotSoap.Plot_SinglePanelAsync(highlight_system.ServiceReferencePlot.Plot_SinglePanelRequest request) {
            return base.Channel.Plot_SinglePanelAsync(request);
        }
        
        public System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.Plot_SinglePanelResponse> Plot_SinglePanelAsync(string site, string macid, string lotnum, string piece_num, string defectcode) {
            highlight_system.ServiceReferencePlot.Plot_SinglePanelRequest inValue = new highlight_system.ServiceReferencePlot.Plot_SinglePanelRequest();
            inValue.Body = new highlight_system.ServiceReferencePlot.Plot_SinglePanelRequestBody();
            inValue.Body.site = site;
            inValue.Body.macid = macid;
            inValue.Body.lotnum = lotnum;
            inValue.Body.piece_num = piece_num;
            inValue.Body.defectcode = defectcode;
            return ((highlight_system.ServiceReferencePlot.SinglePanelPlotSoap)(this)).Plot_SinglePanelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        highlight_system.ServiceReferencePlot.Plot_AllSinglePanelResponse highlight_system.ServiceReferencePlot.SinglePanelPlotSoap.Plot_AllSinglePanel(highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequest request) {
            return base.Channel.Plot_AllSinglePanel(request);
        }
        
        public bool Plot_AllSinglePanel(string site, string macid, string lotnum, string defectcode) {
            highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequest inValue = new highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequest();
            inValue.Body = new highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequestBody();
            inValue.Body.site = site;
            inValue.Body.macid = macid;
            inValue.Body.lotnum = lotnum;
            inValue.Body.defectcode = defectcode;
            highlight_system.ServiceReferencePlot.Plot_AllSinglePanelResponse retVal = ((highlight_system.ServiceReferencePlot.SinglePanelPlotSoap)(this)).Plot_AllSinglePanel(inValue);
            return retVal.Body.Plot_AllSinglePanelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.Plot_AllSinglePanelResponse> highlight_system.ServiceReferencePlot.SinglePanelPlotSoap.Plot_AllSinglePanelAsync(highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequest request) {
            return base.Channel.Plot_AllSinglePanelAsync(request);
        }
        
        public System.Threading.Tasks.Task<highlight_system.ServiceReferencePlot.Plot_AllSinglePanelResponse> Plot_AllSinglePanelAsync(string site, string macid, string lotnum, string defectcode) {
            highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequest inValue = new highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequest();
            inValue.Body = new highlight_system.ServiceReferencePlot.Plot_AllSinglePanelRequestBody();
            inValue.Body.site = site;
            inValue.Body.macid = macid;
            inValue.Body.lotnum = lotnum;
            inValue.Body.defectcode = defectcode;
            return ((highlight_system.ServiceReferencePlot.SinglePanelPlotSoap)(this)).Plot_AllSinglePanelAsync(inValue);
        }
    }
}
