<%@ Page Language="C#" AutoEventWireup="true" CodeFile="test_01.aspx.cs" Inherits="Book_Sample_Ch18_FileUpload_ASHX_test" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            color: #FF0000;
        }
        .auto-style2 {
            color: #000000;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        讀取二進位（Binary）的圖片檔<br />
        <br />
        資料來源：<a href="http://www.cnblogs.com/travelcai/archive/2007/09/25/904767.html">http://www.cnblogs.com/travelcai/archive/2007/09/25/904767.html</a><br />
        <br />
        <br />
        <br />
        <asp:Image ID="Image1" runat="server" />
        <br />
        <span class="auto-style1"><strong>這張圖片是由 test_01.ashx提供的，請看後置程式碼 -- Page_Load事件。<br />
        </strong></span><span class="auto-style2">
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        =====================================================================<br />
        如果要從<strong>資料庫</strong>裡面，讀取二進位的圖片檔，請參閱：<br />
        </span><span class="auto-style1"><span class="auto-style2"><a href="http://www.cnblogs.com/travelcai/archive/2007/09/27/907203.html">http://www.cnblogs.com/travelcai/archive/2007/09/27/907203.html</a></span></span><br />
        <br />
        ASHX檔裡面的程式：<br />
        =====================================================================<br />
        <span style="line-height: 19px; color: rgb(0, 0, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">&lt;%@&nbsp;WebHandler&nbsp;Language=&quot;C#&quot;&nbsp;Class=&quot;ImageHandler&quot;&nbsp;%&gt;<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/None.gif" style="border: 0px;" /><br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/None.gif" style="border: 0px;" /></span><span style="line-height: 19px; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 255);">using</span><span style="line-height: 19px; color: rgb(0, 0, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">&nbsp;System;<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/None.gif" style="border: 0px;" /></span><span style="line-height: 19px; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 255);">using</span><span style="line-height: 19px; color: rgb(0, 0, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">&nbsp;System.Web;<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/None.gif" style="border: 0px;" /></span><span style="line-height: 19px; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 255);">using</span><span style="line-height: 19px; color: rgb(0, 0, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">&nbsp;System.Data;<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/None.gif" style="border: 0px;" /></span><span style="line-height: 19px; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 255);">using</span><span style="line-height: 19px; color: rgb(0, 0, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">&nbsp;System.Data.SqlClient;<br />
        <img id="Codehighlighter1_175_1492_Open_Image" align="top" alt="" onclick="code_collapse_toggle(this);" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedBlockStart.gif" style="border: 0px;" /></span><span style="line-height: 19px; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 255);">public</span><span style="line-height: 19px; color: rgb(0, 0, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">&nbsp;</span><span style="line-height: 19px; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 255);">class</span><span style="line-height: 19px; color: rgb(0, 0, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">&nbsp;ImageHandler&nbsp;:&nbsp;IHttpHandler&nbsp;</span><span id="Codehighlighter1_175_1492_Open_Text" style="line-height: 19px; color: rgb(0, 0, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><span style="line-height: 1.5; color: rgb(0, 0, 0);">{<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">public</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">void</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;ProcessRequest&nbsp;(HttpContext&nbsp;context)&nbsp;<br />
        <img id="Codehighlighter1_240_1399_Open_Image" align="top" alt="" onclick="code_collapse_toggle(this);" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedSubBlockStart.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;</span><span id="Codehighlighter1_240_1399_Open_Text" style="line-height: 1.5;"><span style="line-height: 1.5; color: rgb(0, 0, 0);">{<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 128, 0);">//获取雇员ID。<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" /></span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">string</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;id&nbsp;=&nbsp;context.Request.QueryString[&quot;id&quot;];<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 128, 0);">//这里可以使用我在上一个例子中读图片的文件的例子来代替。<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//altimageData的作用是数据库中不存在照片数据的时候可以<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//显示这个默认的图片。我在这里就用它来代替了。没有实际作用。<br />
        <strong>
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" /></strong></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><strong>&nbsp;<br />
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></span><span style="line-height: 1.5; color: rgb(0, 0, 255);"><strong>byte</strong></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><strong>[]&nbsp;altimageData&nbsp;=&nbsp;</strong></span><span style="line-height: 1.5; color: rgb(0, 0, 255);"><strong>new</strong></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span><span style="line-height: 1.5; color: rgb(0, 0, 255);"><strong>byte</strong></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><strong>[1];<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></span><span style="line-height: 1.5; color: rgb(0, 0, 255);"><strong>byte</strong></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><strong>[]&nbsp;imageData&nbsp;=&nbsp;altimageData;<br />
        </strong>
        <br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">using</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;(SqlConnection&nbsp;conn&nbsp;=&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">new</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings[&quot;NorthwindConnectionString&quot;].ConnectionString))<br />
        <img id="Codehighlighter1_690_1287_Open_Image" align="top" alt="" onclick="code_collapse_toggle(this);" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedSubBlockStart.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span id="Codehighlighter1_690_1287_Open_Text" style="line-height: 1.5;"><span style="line-height: 1.5; color: rgb(0, 0, 0);">{<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SqlCommand&nbsp;comm&nbsp;=&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">new</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;SqlCommand(&quot;SELECT&nbsp;Photo&nbsp;FROM&nbsp;Employees&nbsp;WHERE&nbsp;EmployeeID&nbsp;=&nbsp;@EmployeeID&quot;,&nbsp;conn);<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SqlParameter&nbsp;parm&nbsp;=&nbsp;comm.Parameters.Add(&quot;@EmployeeID&quot;,&nbsp;SqlDbType.Int,&nbsp;4);<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parm.Value&nbsp;=&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">int</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">.Parse(id);<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;conn.Open();&nbsp;<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">using</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;(SqlDataReader&nbsp;rdr&nbsp;=&nbsp;comm.ExecuteReader(CommandBehavior.SingleRow))<br />
        <img id="Codehighlighter1_1068_1267_Open_Image" align="top" alt="" onclick="code_collapse_toggle(this);" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedSubBlockStart.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span id="Codehighlighter1_1068_1267_Open_Text" style="line-height: 1.5;"><span style="line-height: 1.5; color: rgb(0, 0, 0);">{<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">if</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;(rdr.Read())<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 128, 0);">//为了防止你读的数据是空的而做的。如果没有图片就使用替代图片来代替。<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" /></span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;imageData&nbsp;=&nbsp;(rdr[0]&nbsp;==&nbsp;System.DBNull.Value)&nbsp;?&nbsp;<strong>altimageData&nbsp;:&nbsp;(</strong></span><span style="line-height: 1.5; color: rgb(0, 0, 255);"><strong>byte</strong></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><strong>[])rdr[0]</strong>;<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedSubBlockEnd.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}</span></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedSubBlockEnd.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}</span></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 128, 0);">//写入图片信息到输出流中。<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" /></span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context.Response.OutputStream.Write(imageData,&nbsp;78,&nbsp;imageData.Length&nbsp;-&nbsp;78);<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedSubBlockEnd.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;}</span></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" /><br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">public</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">bool</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;IsReusable<br />
        <img id="Codehighlighter1_1433_1489_Open_Image" align="top" alt="" onclick="code_collapse_toggle(this);" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedSubBlockStart.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;</span><span id="Codehighlighter1_1433_1489_Open_Text" style="line-height: 1.5;"><span style="line-height: 1.5; color: rgb(0, 0, 0);">{<br />
        <img id="Codehighlighter1_1447_1483_Open_Image" align="top" alt="" onclick="code_collapse_toggle(this);" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedSubBlockStart.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">get</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;</span><span id="Codehighlighter1_1447_1483_Open_Text" style="line-height: 1.5;"><span style="line-height: 1.5; color: rgb(0, 0, 0);">{<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">return</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">&nbsp;</span><span style="line-height: 1.5; color: rgb(0, 0, 255);">false</span><span style="line-height: 1.5; color: rgb(0, 0, 0);">;<br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedSubBlockEnd.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}</span></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedSubBlockEnd.gif" style="border: 0px;" />&nbsp;&nbsp;&nbsp;&nbsp;}</span></span><span style="line-height: 1.5; color: rgb(0, 0, 0);"><br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/InBlock.gif" style="border: 0px;" /><br />
        <img align="top" alt="" src="http://www.cnblogs.com/Images/OutliningIndicators/ExpandedBlockEnd.gif" style="border: 0px;" />}</span></span></div>
        
    </form>
</body>
</html>
